# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.enum
import registry.models.options
import registry.utility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.TextField()),
                ('admitted_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('providers', registry.utility.models.SeparatedValuesField()),
                ('side_effects', registry.utility.models.SeparatedValuesField()),
                ('msdsLink', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('identifiers', models.ForeignKey(on_delete=models.SET(registry.utility.models.Dictionary.empty), to='registry.Dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Dictionary')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('images', registry.utility.models.SeparatedValuesField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('refills', models.PositiveIntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(max_length=1)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[(0, django_enumfield.enum.Value('MALE', 0, 'M', registry.models.options.Gender)), (1, django_enumfield.enum.Value('FEMALE', 1, 'F', registry.models.options.Gender))], default='M', max_length=1)),
                ('password', models.TextField()),
                ('security_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.User')),
                ('is_sysadmin', models.BooleanField(default=False)),
            ],
            bases=('registry.user',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.User')),
                ('hospitals', models.ManyToManyField(related_name='provider_to', to='registry.Hospital')),
            ],
            bases=('registry.user',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.User')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Hospital')),
            ],
            bases=('registry.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registry.User')),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('blood_type', models.CharField(choices=[(0, django_enumfield.enum.Value('A', 0, 'A', registry.models.options.BloodType)), (1, django_enumfield.enum.Value('B', 1, 'B', registry.models.options.BloodType)), (2, django_enumfield.enum.Value('AB', 2, 'AB', registry.models.options.BloodType)), (3, django_enumfield.enum.Value('O', 3, 'O', registry.models.options.BloodType))], default='O', max_length=2)),
                ('insurance', models.CharField(choices=[('Self Insured', 'Self Insured'), ('Blue Cross Blue Shield', 'Blue Cross Blue Shield'), ('Super Legit MI', 'Super Legit Medical Insurance'), ('Not Legit MI', 'Not Legit Medical Insurance')], default='Self Insured', max_length=40)),
            ],
            bases=('registry.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='cur_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_user_cur_hospital', to='registry.Hospital'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='time_range',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registry.TimeRange'),
        ),
        migrations.AddField(
            model_name='admissioninfo',
            name='admission_time',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='registry.TimeRange'),
        ),
        migrations.AddField(
            model_name='admissioninfo',
            name='prescriptions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registry.Dictionary'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_status', to='registry.AdmissionInfo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pref_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_patient_pref_hospital', to='registry.Hospital'),
        ),
        migrations.AddField(
            model_name='admissioninfo',
            name='doctors',
            field=models.ManyToManyField(to='registry.Doctor'),
        ),
    ]
