"""
Django settings for HealthNet project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1&!+0x75m@)f+-lqdwg3(=p2n=16m0o6j+!wa)8h75+_wut3kz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'djangobower',
    'registry.apps.RegistryConfig',
    'rules.apps.AutodiscoverRulesConfig',
    'jet.dashboard',
    'jet',
    'sass_processor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'axes',
    'debug_toolbar',
    # 'hijack',
    'compat',
    'crispy_forms',
    'annoying',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.FailedLoginMiddleware',
]

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)

ROOT_URLCONF = 'HealthNet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HealthNet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = False


SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_SSL_REDIRECT = False
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    CSRF_COOKIE_HTTPONLY = True

STATICFILES_FINDERS = {
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
    'sass_processor.finders.CssFinder'
}

BOWER_INSTALLED_APPS = {
    'jquery',
    'Chart.js',
    'timesheet.js',
    'bootstrap',
    'lodash',
    'pikaday',
}

BOWER_COMPONENTS_ROOT = os.path.join(BASE_DIR)
STATIC_ROOT = os.path.join(BASE_DIR, 'private_static')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# AXES SETTINGS - Do not change without permission
AXES_LOGIN_FAILURE_LIMIT = 3
AXES_LOCK_OUT_AT_FAILURE = True
AXES_USE_USER_AGENT = False
AXES_COOLOFF_TIME = None
AXES_LOCKOUT_TEMPLATE = None
AXES_LOCKOUT_URL = None
AXES_VERBOSE = True
AXES_USERNAME_FROM_FIELD = 'username'
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = False

CRISPY_FAIL_SILENTLY = not DEBUG
CRISPY_TEMPLATE_PACK = 'bootstrap'

## Mute Deprecation Warnings
import logging, copy
from django.utils.log import DEFAULT_LOGGING


LOGGING = copy.deepcopy(DEFAULT_LOGGING)
LOGGING['filters']['suppress_deprecated'] = {
    '()': 'HealthNet.settings.SuppressDeprecated'
}
LOGGING['handlers']['console']['filters'].append('suppress_deprecated')

class SuppressDeprecated(logging.Filter):
    def filter(self, record):
        WARNINGS_TO_SUPPRESS = [
            'RemovedInDjango110Warning',
            'RemovedInDjango19Warning'
        ]
        # Return false to suppress message.
        return not any([warn in record.getMessage() for warn in WARNINGS_TO_SUPPRESS])

LOG_DIR = os.path.join(BASE_DIR, 'logs')
DEBUG_LOG = os.path.join(LOG_DIR, 'hn_debug.log')
ACTIVITY_LOG = os.path.join(LOG_DIR, 'hn_activity.log')
ERROR_LOG = os.path.join(LOG_DIR, 'hn_error.log')

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

if not os.path.exists(DEBUG_LOG):
    open(DEBUG_LOG, 'w').close()

if not os.path.exists(ACTIVITY_LOG):
    open(ACTIVITY_LOG, 'w').close()

if not os.path.exists(ERROR_LOG):
    open(ERROR_LOG, 'w').close()

#I have no idea what I'm doing
LOGGING['formatters'] = {}
LOGGING['formatters']['activity'] = {
    'format': '[%(levelname)s] %(pathname)s <%(funcName)s>[%(lineno)s] : %(message)s',
}
LOGGING['formatters']['debug'] = {
    'format': '[%(levelname)s] %(pathname)s <%(funcName)s>[%(lineno)s] : %(message)s',
}

LOGGING['handlers']['debug'] = {
    'level': 'DEBUG',
    'class': 'logging.handlers.TimedRotatingFileHandler',
    'filename': DEBUG_LOG,
    'formatter': 'debug',
    'backupCount': 48,
    'when': 'H',
    'filters': [],
}
LOGGING['handlers']['debug']['filters'].append('suppress_deprecated')

LOGGING['handlers']['activity'] = {
    'level': 'INFO',
    'class': 'logging.handlers.TimedRotatingFileHandler',
    'filename': ACTIVITY_LOG,
    'formatter': 'activity',
    'backupCount': 48,
    'when': 'H',
}

LOGGING['handlers']['error'] = {
    'level': 'ERROR',
    'class': 'logging.handlers.TimedRotatingFileHandler',
    'filename': ERROR_LOG,
    'formatter': 'activity',
    'backupCount': 48,
    'when': 'H',
}

LOGGING['loggers']['hn.activity'] = {
    'handlers': ["activity", "error", "debug"],
    'level': 'INFO',
    'propagate': True,
}

LOGGING['loggers']['hn.request'] = {
    'handlers': ["error", "activity", "debug"],
    'level': 'ERROR',
    'propagate': False,
}

LOGGING['loggers']['hn.security'] = {
    'handlers': ["error", "activity"],
    'level': 'ERROR',
    'propagate': False,
}

LOGGING['loggers']['py.warnings'] = {
    'handlers': ["console", "debug"],
}

AXES_LOGGER = 'hn.security'
